spring:
  config:
    activate:
      on-profile: core2

  datasource:
    url: jdbc:postgresql://localhost:5432/db_example2
    username: postgres
    password: 12345
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect